services:
  streamlit:
    image: riskvision-base:latest
    build:
      context: backend
      dockerfile: Dockerfile  
    ports:
      - "8501:8501"
    working_dir: /RiskVision/streamlit
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  flask:
    image: riskvision-base:latest
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /RiskVision
    command: ["python", "app.py"]  
  frontend:
    image: riskvision-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    working_dir: /RiskVision/frontend